### ISSUE TITLE
WSL环境下无法成功构建项目

### ISSUE THREAD

**Issue by zlyc8** [laoyin/freeswitch_admin_ui#2]
1、使用debian 以及ubuntu均无法构建项目，构建时提示以下内容，但程序未退出。
` ERROR  Failed to compile with 4 errors                                                                       2:20:27 AM

These dependencies were not found:

* @/views/ivr-add/index in ./src/router/index.js
* @/views/ivr/index in ./src/router/index.js
* @/views/record/index in ./src/router/index.js

To install them, you can run: npm install --save @/views/ivr-add/index @/views/ivr/index @/views/record/index

This relative module was not found:

* ./modules/callData in ./src/store/index.js`

2、使用NETSTAT -ANTP 查看监听端口，node程序仅监听了9529端口，未监听9528端口
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9529            0.0.0.0:*               LISTEN      5018/node
tcp        0      0 172.28.190.159:9529     172.28.176.1:51414      ESTABLISHED 5018/node
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -

3、WEB网页可登录端口号为9529的页面，但提示以下内容
`Failed to compile.

./src/store/index.js
Module not found: Error: Can't resolve './modules/callData' in '/home/freeswitch_admin_ui-master/src/store'`

**Comment by coder-rance** [comment]
我也试了一下，他的项目缺少文件，跑不起来

**Comment by a83988029** [comment]
我也是这样，作者有部分页面没上传，要在router/index.js里面把他们删掉

**Comment by laoyin** [comment]
代码更新了
